const {chromium}=require('/tmp/node_modules/playwright');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:2,storageState:__dirname+'/private/auth.json'});
 const page=await context.newPage();
 await page.goto('https://crm.ancsports.net/object/company/68a366db-2630-40ea-a706-472a0a0a6ec9',{waitUntil:'domcontentloaded'});
 await page.waitForTimeout(9000);
 const general=page.getByText('General',{exact:true}).first();
 await general.click();
 await page.waitForTimeout(600);
 const business=page.getByText('Business',{exact:true}).first();
 const fields=['subsidiaryLifetimeValue','subsidiaryLifetimeMargin','subsidiaryWonDealCount','subsidiaryLtvLastRollupAt'];
 const boxes={};
 for(const field of fields)boxes[field]=await page.locator('[id="label-68a366db-2630-40ea-a706-472a0a0a6ec9-'+field+'"]').boundingBox();
 const last=boxes[fields[3]];
 if(!last)throw new Error('Business is not expanded.');
 const clip={x:221,y:48,width:347,height:Math.ceil(last.y+last.height+12-48)};
 await page.mouse.move(700,60);
 await page.screenshot({path:__dirname+'/frames/02-business.png',clip});
 await business.click();
 await page.waitForTimeout(500);
 await page.screenshot({path:__dirname+'/frames/01-start.png',clip});
 await business.click();
 await page.waitForTimeout(500);
 await page.locator('[id="label-68a366db-2630-40ea-a706-472a0a0a6ec9-subsidiaryLifetimeMargin"]').hover();
 await page.waitForTimeout(700);
 await page.screenshot({path:__dirname+'/frames/03-types.png',clip});
 await page.locator('[id="label-68a366db-2630-40ea-a706-472a0a0a6ec9-subsidiaryLtvLastRollupAt"]').hover();
 await page.waitForTimeout(700);
 await page.screenshot({path:__dirname+'/frames/04-refresh.png',clip});
 await page.mouse.move(700,60);
 await general.click();
 fs.writeFileSync(__dirname+'/review/capture.json',JSON.stringify({url:page.url(),clip,boxes,captureMode:'Cropped real production screenshots; native section toggles and label hovers'},null,2));
 await browser.close();console.log('Four real Company panel captures saved.');
})().catch(e=>{console.error(e.message);process.exit(1)});
