const {chromium}=require('/tmp/node_modules/playwright');
const fs=require('node:fs');
const base=process.env.ACADEMY_BASE||'https://docs.ancsports.net';
const root=process.env.WALKTHROUGH_ROOT||__dirname;
const route='/docs/training/core/subsidiary-ltv';
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const checks=[];const errors=[];
 const check=(name,pass)=>{checks.push({name,pass:!!pass});console.log(pass?'PASS':'FAIL',name);if(!pass)throw new Error(name)};
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/academy',{waitUntil:'networkidle'});
 const card=page.locator(`a[href="${route}"]`);check('One Academy card',await card.count()===1);await card.scrollIntoViewIfNeeded();await card.click();
 await page.getByRole('heading',{name:'Find subsidiary lifetime value',level:1}).waitFor();
 check('Correct lesson route',new URL(page.url()).pathname===route);
 await page.locator('script[src*="abc-umami"]').first().waitFor({state:'attached',timeout:15000});
 check('Tracking script present',await page.locator('script[src*="abc-umami"]').count()>0);
 const video=page.locator('video');await video.scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('video').readyState>=2);
 const media=await video.evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight,source:v.currentSrc}));
 const expected=Number(require('node:child_process').execFileSync('ffprobe',['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',root+'/output/subsidiary-ltv.mp4'],{encoding:'utf8'}));
 check('Full HD verified walkthrough duration',media.width===1920&&media.height===1080&&Math.abs(media.duration-expected)<0.2);
 await video.evaluate(async v=>{v.muted=false;v.volume=1;await v.play()});
 await page.waitForFunction(()=>{const v=document.querySelector('video');return v.currentTime>2&&!v.paused&&!v.muted});check('Playback with sound enabled',true);
 await video.evaluate(v=>{v.pause();v.currentTime=v.duration/2});await page.waitForTimeout(600);check('Midpoint seek',await video.evaluate(v=>v.readyState>=2));
 await page.screenshot({path:root+'/review/academy-desktop.png'});
 const captions=await page.request.get(base+'/videos/training/subsidiary-ltv.vtt');check('English captions',captions.ok()&&(await captions.text()).startsWith('WEBVTT'));
 await video.evaluate(async v=>{v.currentTime=v.duration-1;await v.play()});await page.waitForFunction(()=>document.querySelector('video').ended,{},{timeout:10000});check('Plays through ending',true);
 await page.setViewportSize({width:390,height:844});await video.scrollIntoViewIfNeeded();await video.evaluate(v=>{v.currentTime=11});await page.waitForTimeout(600);
 check('Phone fits screen',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('Phone video visible',(await video.boundingBox()).width>250);
 await page.screenshot({path:root+'/review/academy-phone.png'});check('No runtime errors',errors.length===0);
 fs.writeFileSync(root+'/review/'+(base.includes('localhost')?'preview':'live')+'-academy.json',JSON.stringify({base,route,media,checks,errors},null,2));await browser.close();
})().catch(e=>{console.error(e.message);process.exit(1)});
